name: example
description: "Exemplo de Utilização do Plugin em Flutter para integração com o PlugPagServiceWrapper da PagSeguro."

publish_to: 'none'
version: 1.0.9

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  pagseguro_smart:
    path: ../
  provider: ^6.1.5+1
  flutter_masked_text2: ^0.9.1
  bot_toast: ^4.1.3
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  #integration_test:
    #sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true